### ISSUE TITLE
Where is the app?

### ISSUE THREAD

**Issue by davidvasandani** [shirosaidev/airbnbbot#1]
This looks like a great project based on the readme and I'd love to contribute but I don't see any code! Please let me know if you're planning on publishing what you have so far. Cheers!

**Comment by shirosaidev** [comment]
I've had no time to work on this code in a while, I just committed what I was working on but it's far from finished.. any contributions are appreciated.

**Comment by shirosaidev** [comment]
Also, by default runs in training and testing mode and also line 301 needs to be uncommented if you want to actually send messages to guests, which I don't recommend yet until the code is more mature..

**Comment by davidvasandani** [comment]
Thanks @shirosaidev
